import Head from 'next/head';
import Link from 'next/link';
import { blogPosts } from '../lib/data';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {blogPosts.map((item) => (
          <BlogListItem key={item.slug} {...item} />
        ))}
      </div>
    </div>
  );
};

function BlogListItem({ slug, title, date, content}) {
  return (
    <div>
        <div>
          <div><Link href={`/blog/${slug}`}><a>{title}</a></Link></div>
          <div>{date.toString()}</div>
          <div>{content}</div>
        </div>
      ))}
    </div>
  )
}
